docker/datahub-actions/Dockerfile
To fix https://github.com/datahub-project/datahub/issues/4741
Tested on local
```
aseembansal@Aseems-MacBook-Pro datahub-actions % docker run -it --rm tmp bash                                
datahub@c138716c03e3:/$ java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Zulu 8.62.0.19-CA-linux_aarch64) (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Zulu 8.62.0.19-CA-linux_aarch64) (build 25.332-b09, mixed mode)
```
=> fix(build): install java 8 by default in image

datahub-actions/src/datahub_actions/plugin/transform/filter/filter_transformer.py, docker/config/executor.yaml
This PR adds an implicit conversion of nested JSON strings to dicts (if possible), to allow filtering by nested objects/properties e.g. the value field of the GenericAspect of the MetadataChangeLog event. Using this it is possible to define a filter for the corresponding executorId (if the events with the "wrong" executor ids are not filtered the dispatcher would raise an error (see [here](https://github.com/acryldata/datahub-actions/blob/6d0d6d4914f11e85f71a38e6b84662dc70dd83a2/datahub-actions/src/datahub_actions/plugin/action/execution/executor_action.py#L146)).
See also the [executor.yaml](https://github.com/Masterchen09/datahub-actions/blob/ba8667f18d0bbda720dfe18a298b9227a24d2b79/docker/config/executor.yaml#L29-L34) for an example.
=> feat(plugin): update filter transformer to allow filtering by nested JSONs

datahub-actions/src/datahub_actions/plugin/action/execution/executor_action.py, docker/config/executor.yaml
This PR add an optional task config to the executor action. Using this it is possible to implement different task types and use them without the need to also implement an action which uses this new task type.
See also the [executor.yaml](https://github.com/Masterchen09/datahub-actions/blob/f69e4a97f50c6e8637e2f7a8a6706497957cb316/docker/config/executor.yaml#L34-L37) for an example.
=> feat(plugin): add configurable task config to the executor action

docker/datahub-actions/Dockerfile
This PR prevents some extra package downloads from PyPI.
Unfortunately, this yields only a modest perf improvement and is most impactful when the container is running with a slow internet connection, which likely isn't the case.
I ran a small and unscientific performance test of setting up a fresh venv: 
```bash
python -m venv venv
source venv/bin/activate
pip install --upgrade pip wheel setuptools
time pip install acryl-datahub[snowflake]
```
- Current (no root cache preservation): 1m9.474s
- With this PR: 0m58.968s
- When all dependencies are already downloaded to cache: 0m43.000s
As such, it seems much of the time is spent determining cache freshness and installing from cache into the `venv` - longer term, we'll need to keep warm venv's ready for use to maintain responsiveness.
=> perf(docker): retain root user's build cache in docker image

datahub-actions/setup.py
- Bumping acryl-executor to v0.0.3.2 to get debug mode fix.
=> bump(ae): Bumping acryl-executor to 0.0.3.2 

datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py
We use our own ca certs for our kafka schema registry so we need to configure our "ingestion_executor" with the cert path. For example:
```yaml
name: "ingestion_executor" 
source:
type: "kafka"
config:
connection:
bootstrap: ${KAFKA_BOOTSTRAP_SERVER:-localhost:9092}
schema_registry_url: ${SCHEMA_REGISTRY_URL:-http://localhost:8081}
schema_registry_config:
ssl.ca.location: "/usr/local/share/ca-certificates/mycompany/my-certs.crt"
```
This PR passes these setting to the SchemaRegistryClient
=> feat(schema-registry): respect schema_registry_config

docs/guides/developing-an-action.md
Found this error while trying to reproduce the custom_action example and failing.
=> fix(docs): fix import of EventEnvelope in custom_action example code

datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py
Deploying multiple kafka source action pipelines causes the following error to appear:
```
ValueError: Duplicated timeseries in CollectorRegistry: {'kafka_offset'}
```
and 
```
ValueError: Duplicated timeseries in CollectorRegistry: {'kafka_messages_count', 'kafka_messages_count_created', 'kafka_messages_count_total'}
```
The fix adds a namespace to the metrics to avoid name collisions.
_This occured when deploying without enabling metrics_
=> fix(kafka-event-source): add namespace to avoid duplicates error when using multiple pipelines

datahub-actions/src/datahub_actions/plugin/action/execution/executor_action.py
This PR replaces the task_config configuration option which I have added in PR #22 with task_configs, a variant with a list of task configs. With the introduction of the connection test feature in PR #29, it is not possible anymore to provide a custom task configuration (and different task types) for both tasks as the test connection task config is always added to the executor config.
As I am pretty sure that I am currently the only one which is using the task_config configuration option I have replaced it without keeping the old configuration option (and maybe merge the old configuration option with the new configuration option). If someone disagrees on that I could also prepare a variant where we could keep the old configuration option. Additionally I think if someone else is currently …
=> fix(plugin): replace task_config with task_configs

docker/actions.env, docker/config/executor.yaml, docker/datahub-actions/Dockerfile, docs/actions/executor.md, examples/executor.yaml
This PR adds a new environment variable, `DATAHUB_GMS_PROTOCOL`, which allows you to specify either `http` or `https` for the connection to GMS. It defaults to `http` everywhere `DATAHUB_GMS_HOST` was set/used before, and a brief read of the code doesn't reveal any incompatibilities with this strategy.
One callout is that this is slightly different from the Java apps which use `DATAHUB_GMS_USE_SSL` as their env var, however there wasn't a good way to use a boolean for this use case as it's being parsed by `pyyaml` and there's no way to create an inline conditional.
=> feat: allow specifying https protocol for GMS connection

datahub-actions/src/datahub_actions/cli/actions.py
The current output will write any credentials in the yaml configs to the logs as plain text, which is a security risk. This PR removes that risk by logging the configuration name to the output on error rather than the full configuration with plaintext secrets.
This affects anyone who uses the metadata system authentication for auth to GMS, and anyone who uses a Kafka cluster that has some sort of username/password auth.
=> fix: remove credential plaintext logging on init

datahub-actions/setup.py, datahub-actions/src/datahub_actions/action/action_registry.py, datahub-actions/src/datahub_actions/plugin/action/metadata_change_sync/metadata_change_sync.py, datahub-actions/tests/unit/plugin/action/metadata_change_sync/test_metadata_change_sync.py, docs/actions/metadata_change_sync.md, examples/metadata_change_sync.yaml
This PR implements a new action that can listen to the `MetadataChangeLogEvent_v1` events and convert it to `MetadataChangeProposal` and use the Python emitter SDK to emit the proposal to another datahub instance.
The configuration file takes `gms_server` and `gms_auth_token` to emit the proposal to another datahub instance, since `MetadataChangeProposal` currently only supports the `UPSERT` change type, we'll only focus on `MetadataChangeLogEvent_v1` with the `UPSERT` type.
Tests and doc for the changes have been added
=> feat(action): add metadata_change_sync action to sync two datahub instances

docker/datahub-actions/start.sh
The current startup script doesnt allow someone running the actions image to change the path it loads configuration yaml files from. This is an important feature because some consumers will need to load files from something like a mounted EFS volume rather than just load the config files that are baked into the container by default.
=> feat: allow overriding docker config yaml paths

datahub-actions/src/datahub_actions/entrypoints.py, datahub-actions/src/datahub_actions/plugin/action/metadata_change_sync/metadata_change_sync.py
This PR has the following improvement for logging:
1. The current stream_handler by default logs everything to `stderr`, it's not a desirable behavior when we want to distinguish errors from info, for example in logging explorer in GKE. To address this, we separate into `info_handler` which directs output to `stdout`, and `error_handler` directs output to `stderr`. By adding a filter class `LogFilter` to `info_handler` we'll be able to let through messages below the level we set.
2. The current datahub-actions logging only logs to the console but not keeping a record in file, the `start.sh` in `docker/datahub-actions` has `touch /tmp/datahub/logs/actions/actions.out` that the file is created but it's never being used. We use `TimedRotatingFileHandler` that outputs the logging to this file …
=> feat(logging): Improve general logging and add more logging in metadata change sync action

datahub-actions/setup.py
Seems like there's an issue in 0.0.3.10.
=> chore: pin acryl-executor version

datahub-actions/setup.py, datahub-actions/src/datahub_actions/cli/actions.py, datahub-actions/src/datahub_actions/utils/name_resolver.py, datahub-actions/tests/unit/pipeline/test_pipeline.py
Needed as a follow up on https://github.com/datahub-project/datahub/pull/8696
=> fix: use `_resolve_element` method in config load

datahub-actions/setup.py, datahub-actions/src/datahub_actions/cli/actions.py
Was broken by https://github.com/datahub-project/datahub/pull/9477
=> fix: upgrade config loading logic to new acryl-datahub

datahub-actions/setup.py, datahub-actions/src/datahub_actions/pipeline/pipeline.py, datahub-actions/src/datahub_actions/pipeline/pipeline_util.py, datahub-actions/src/datahub_actions/plugin/action/utils/term_resolver.py, datahub-actions/src/datahub_actions/utils/name_resolver.py
This should enable pydantic 2 support. The acryl-datahub kafka source still requires pydantic v2, but the datahub-kafka sink does not. We only need the sink capabilities here.
Slack ref: https://datahubspace.slack.com/archives/CV2KB471C/p1706298872346799?thread_ts=1706201071.771369&cid=CV2KB471C
=> fix: tweak datahub-kafka requirement

docker/config/executor.yaml, docker/config/slack_action.yaml, docker/config/teams_action.yaml
To have configurable consumer groups, this PR introduces three new environment variables which are used for the names of the three existing pipelines - the names of the pipelines are used for the consumer groups:
DATAHUB_ACTIONS_INGESTION_EXECUTOR_CONSUMER_GROUP_ID (ingestion_executor)
DATAHUB_ACTIONS_SLACK_CONSUMER_GROUP_ID (datahub_slack_action)
DATAHUB_ACTIONS_TEAMS_CONSUMER_GROUP_ID (datahub_teams_action)
If the environment variables are not provided the existing pipeline names will be used by default.
There will be another PR in the datahub-helm repository which will use these environment variables.
edit: The [other PR](https://github.com/acryldata/datahub-helm/pull/436) in the datahub-helm repository.
=> feat: add configuration for Kafka consumer groups via environment variables

datahub-actions/src/datahub_actions/pipeline/pipeline.py, datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py, datahub-actions/src/datahub_actions/plugin/source/kafka/utils.py, datahub-actions/src/datahub_actions/source/event_source.py, datahub-actions/tests/unit/test_helpers.py, gradle/wrapper/gradle-wrapper.properties
* Reliability: check/retry commit failures. By default, commit is asynchronous, and no error checking/logging is performed. This PR converts the commit call to a synchronous call, checks if any partition failed to commit, logs the errors, and retries failed commits.
* Performance: originally, actions consumer commits offset after passing every single message to the user. Commit is very expensive by itself, and it causes a network round-trip, so processing of a heavily backed up topic may take a very long time. This changes the behavior of the consumer such that it only commits after messages that the user cares about, and all other messages are committed periodically, according to the standard auto-commit configuration.
@jjoyce0510
=> Kafka consumer reliability/performance improvements

datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py, docs/sources/kafka-event-source.md
In this PR, we add support for wiring in MCL Timeseries topic to datahub actions. 
Verified that timeseries events are streaming through using the hello_world action when enabled. 
```
{
"event_type": "MetadataChangeLogEvent_v1",
"event": {
"entityType": "assertion",
"entityUrn": "urn:li:assertion:358c683782c93c2fc2bd4bdd4fdb0153",
"changeType": "UPSERT",
"aspectName": "assertionRunEvent",
"aspect": {
"value": "{\"result\":{\"type\":\"SUCCESS\",\"nativeResults\":{}},\"assertionUrn\":\"urn:li:assertion:358c683782c93c2fc2bd4bdd4fdb0153\",\"timestampMillis\":1675155843000,\"asserteeUrn\":\"urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)\",\"runId\":\"2021-12-28T12:00:00Z\",\"partitionSpec\":{\"type\":\"PARTITION\",\"partition\":\"{\\\"category\\\": …
```
=> feat(actions): Adding support for MCL Timeseries

docker/datahub-actions/start.sh
I saw that the CLI of datahub-actions [contains an option](https://github.com/acryldata/datahub-actions/blob/54a568b556fd2b799cd99a25abad3b45f9756c71/datahub-actions/src/datahub_actions/entrypoints.py#L45-L59) to enable a monitoring endpoint - this PR introduces two new environment variables (DATAHUB_ACTIONS_MONITORING_ENABLED and DATAHUB_ACTIONS_MONITORING_PORT) which allows to enable this endpoint when running the Docker image.
There will be a second PR for the datahub-helm repository which will make use of these two environment variables.
edit: Here is the other PR: https://github.com/acryldata/datahub-helm/pull/473
=> feat: add environment variables to configure monitoring in Docker image

.github/workflows/datahub-actions-docker.yml, datahub-actions/setup.py, datahub-actions/src/datahub_actions/api/action_graph.py, datahub-actions/src/datahub_actions/plugin/action/mcl_utils.py, datahub-actions/src/datahub_actions/plugin/action/propagation/__init__.py, datahub-actions/src/datahub_actions/plugin/action/propagation/docs/__init__.py, datahub-actions/src/datahub_actions/plugin/action/propagation/docs/propagation_action.py, datahub-actions/src/datahub_actions/plugin/action/propagation/propagation_utils.py, datahub-actions/src/datahub_actions/plugin/action/stats_util.py, datahub-actions/tests/unit/test_helpers.py, docker/config/doc_propagation_action.yaml, settings.gradle, smoke-test/build.gradle, smoke-test/pyproject.toml, smoke-test/pytest.ini, smoke-test/requests_wrapper/__init__.py, smoke-test/requests_wrapper/utils_requests_wrapper.py, smoke-test/requirements.txt, smoke-test/run-quickstart.sh, smoke-test/smoke.sh, smoke-test/tests/actions/doc_propagation/resources/datasets.yaml, smoke-test/tests/actions/doc_propagation/resources/user_clicks.avsc, smoke-test/tests/actions/doc_propagation/test_propagation.py, smoke-test/tests/conftest.py, smoke-test/tests/consistency_utils.py, smoke-test/tests/utils.py
This PR introduces a new DocPropagationAction for column-level documentation propagation. 
Key features include:
1. Automated propagation of documentation changes to downstream and sibling schema fields
2. Configuration options to enable/disable propagation at global and column levels
3. Support for ADD, MODIFY, and REMOVE operations on documentation
4. Integration with DataHub's event system, processing EntityChangeEvents and MetadataChangeLogs
5. Ability to fetch and apply global settings from DataHub
6. Detailed logging and statistics tracking for monitoring and debugging
As seen in DataHub townhall - https://youtu.be/hdqgjxiW-zI?t=2051
=> feat(actions): add docs propagation action for columns

datahub-actions/src/datahub_actions/pipeline/pipeline.py
The handle failure code is in the while loop, so after a single failure it will run the _handle_failure function. The retries will still happen if the `failure_mode` is set to `CONTINUE`, but if it's set to `THROW` it will throw an exception after the first failure. With these lines outside of the loop, it will still log when an attempt fails and then once all retries are exhausted it will print the actual failure message and throw and exception if set to `THROW` mode.
=> fix(retries): move handle failure code outside of while loop

datahub-actions/setup.py
Will also force a datahub-actions docker build, which will pull in the new base image from https://github.com/datahub-project/datahub/pull/11477
=> chore: remove extraneous deps

datahub-actions/setup.py
kafka plugin [depends](https://github.com/acryldata/datahub-actions/blob/main/datahub-actions/src/datahub_actions/plugin/source/kafka/kafka_event_source.py#L22) on schemaregistry from confluent-kafka package, so its dependencies have to be installed as well
=> Add explicit dependency on confluent-kafka[schemaregistry]

README.md
Adding a reference to the new datahub cloud event source docs in the main readme.
=> docs(): Adding README changes to include datahub cloud event source

README.md
fixing link for DataHub Cloud Event Source
=> Update README.md to fix URL

.github/workflows/datahub-actions-docker.yml
I think the `>` character might cause issues with / get misinterpreted by yaml. Prior to this, smoke tests would always fail in CI, although I'm not sure when things stopped working.
Also makes some tweaks to ensure that smoke tests run on all code changes, and that they use the latest code. If we had this, we would've caught the regression from https://github.com/acryldata/datahub-actions/pull/142.
=> fix(ci): fix docker image save/load

.github/workflows/build-and-test.yml, .github/workflows/datahub-actions-docker.yml, datahub-actions/src/datahub_actions/plugin/action/propagation/docs/propagation_action.py, smoke-test/tests/actions/doc_propagation/test_propagation.py
- When the AI description action sets the Attribution aspect, it doesn’t set the Attribution details that the propagation action expects to have in MCL. This causes the origin to be null, which breaks Doc propagation since it requires a non-empty origin.. This leads to null origin, which in the Doc propagation code can't be empty and fails. 
In this fix, I make sure it is set if it is empty to the entity's urn; in this case, this is where the change request comes from.
- lint fixes
=> fix(propagation): Don't fail in propagation if origin is missing

.github/.codecov.yml, .github/workflows/build-and-test.yml, datahub-actions/pytest.ini, datahub-actions/setup.cfg
Deleted pytest.ini since pytest will look at one of pytest.ini or setup.cfg and was ignoring setup.cfg Moved the one setting in pytest.ini into setup.cfg
=> feat(ci): add code cov tracking

.github/workflows/datahub-actions-docker.yml, docker/datahub-actions/Dockerfile
This makes the docker image about 25% smaller (~800MB).
Before the change the image is about 3.08GB, reported by `docker images` and with the change is is about  2.27GB.
Fixes #157
=> fix: Remove uv cache from docker image
